---
# file: tasks/install.yml

- name: "Grafana > Install apt-transport-https to support https APT downloads"
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: "Grafana > Add Grafana repository key"
  apt_key:
    url: '{{ grafana_apt_key }}'
    state: present
  when: grafana_apt_key | string
  become: yes

- name: "Grafana > Add Grafana repository"
  apt_repository:
    repo: '{{ grafana_apt_url }}'
    state: present
  become: yes

- name: "Grafana > Install package"
  apt:
    name: "{{ grafana_install_packages|default(grafana_install_packages_default, True) }}"
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  become: yes
  notify: grafana started

- name: "Grafana > Ensure Grafana is enabled at boot"
  service:
    name:  grafana-server
    enabled: yes
  become: yes
